abstract class WeaponNames{
  static List<String> weaponNames = [
    'Melee',
    'Classic',
    'Shorty',
    'Frenzy',
    'Ghost',
    'Sheriff',
    'Stinger',
    'Spectre',
    'Bucky',
    'Judge',
    'Bulldog',
    'Guardian',
    'Vandal',
    'Phantom',
    'Marshal',
    'Outlaw',
    'Operator',
    'Ares',
    'Odin',
  ];
  static Map<String, String> weaponCategories = {
    'Melee': 'Melee',
    'Classic': 'Sidearm',
    'Shorty': 'Sidearm',
    'Frenzy': 'Sidearm',
    'Ghost': 'Sidearm',
    'Sheriff': 'Sidearm',
    'Stinger': 'Smg',
    'Spectre': 'Smg',
    'Bucky': 'Shotgun',
    'Judge': 'Shotgun',
    'Bulldog': 'Rifle',
    'Guardian': 'Rifle',
    'Vandal': 'Rifle',
    'Phantom': 'Rifle',
    'Marshal': 'Sniper',
    'Outlaw': 'Sniper',
    'Operator': 'Sniper',
    'Ares': 'Heavy',
    'Odin': 'Heavy',
  };

}